groups:
    - bash
    - developer
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_computer_name
attributes:
    sublime_text_packages:
        -
            name: GoSublime
            source: https://github.com/DisposaBoy/GoSublime.git
            branch: master
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: ST3
        -
            name: ApplySyntax
            source: https://github.com/facelessuser/ApplySyntax.git
            branch: ST3
    git:
        name: juliendsv
        email: julien.dasilva@gmail.com
    osxdefaults:
        computername: juliendsv
    authorization:
        sudo:
            users:
                - juliendsv
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        cask_apps:
            - dropbox
            - evernote
            - spotify
            - caffeine
            - vlc
            - slack
