recipes:
    global:
        - applications::php56
    mac_os_x:
        - applications::sublime_text_3
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
attributes:
    homebrewalt:
        apps:
            - git
            - wget
            - htop-osx
            - rsync
        cask_apps:
            - phpstorm
            - sequel-pro
    gems:
        - sass
        - git-up
        - kstrano
        - deliver
        - crafter
    php-apps:
        - composer
